# Generated by Django 4.0.2 on 2022-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('GSM', models.CharField(blank=True, max_length=10, null=True)),
                ('ICE', models.IntegerField(blank=True, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('denomination', models.CharField(blank=True, max_length=250, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=250, null=True)),
                ('registre_de_commerce', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Clients Morale',
            },
        ),
        migrations.CreateModel(
            name='ClientPhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('gsm', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ICE', models.IntegerField(blank=True, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clients Physiques',
            },
        ),
    ]
