# Generated by Django 3.2.7 on 2021-09-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('GSM', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ICE', models.IntegerField(blank=True, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('denomination', models.CharField(blank=True, max_length=250, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.villes')),
            ],
            options={
                'db_table': 'Clients Physiques',
            },
        ),
        migrations.CreateModel(
            name='ClientMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('GSM', models.CharField(blank=True, max_length=10, null=True)),
                ('cin', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('ICE', models.IntegerField(blank=True, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('denomination', models.CharField(blank=True, max_length=250, null=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.villes')),
            ],
            options={
                'db_table': 'Clients Morale',
            },
        ),
    ]
