# Generated by Django 3.2.7 on 2021-09-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientphysique',
            old_name='GSM',
            new_name='gsm',
        ),
    ]
