# Generated by Django 3.2.7 on 2021-09-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SituationJuridique',
        ),
    ]
