# Generated by Django 3.2.7 on 2021-09-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0002_rename_gsm_clientphysique_gsm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmorale',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='clientmorale',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='clientmorale',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='clientphysique',
            name='denomination',
        ),
        migrations.RemoveField(
            model_name='clientphysique',
            name='raison_sociale',
        ),
        migrations.AddField(
            model_name='clientmorale',
            name='registre_de_commerce',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
