# Generated by Django 3.2.7 on 2021-09-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_clients', '0003_auto_20210927_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmorale',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='clientphysique',
            name='ville',
        ),
    ]
