# Generated by Django 3.2.7 on 2021-09-27 10:55

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'Dexa_tags',
            },
        ),
        migrations.CreateModel(
            name='TypeBien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Villes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('lng', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('type_de_bien', models.IntegerField(blank=True, null=True)),
                ('type_de_reference', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateField(default=datetime.date.today, null=True)),
                ('actualisation', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, null=True, size=None)),
                ('user_editer', models.IntegerField(blank=True, null=True)),
                ('user_valider', models.IntegerField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('surface', models.BigIntegerField(blank=True, null=True)),
                ('prix_unit', models.BigIntegerField(blank=True, null=True)),
                ('prix_total', models.BigIntegerField(blank=True, null=True)),
                ('descriptif', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(max_length=500, null=True)),
                ('is_validate_by_user', models.BooleanField(blank=True, default=False, null=True)),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('chute_fonciere', models.IntegerField(blank=True, null=True)),
                ('rue', models.CharField(max_length=500, null=True)),
                ('is_localized', models.BooleanField(blank=True, default=True, null=True)),
                ('from_mobile', models.BooleanField(blank=True, default=False, null=True)),
                ('from_table', models.CharField(default='D', max_length=1, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.regions')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.villes')),
            ],
            options={
                'db_table': 'Dexa_pin',
            },
        ),
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('descriptif', models.CharField(max_length=40, null=True)),
                ('pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.pin')),
            ],
            options={
                'db_table': 'Dexa_photographies',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('editer_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.pin')),
            ],
            options={
                'db_table': 'Dexa_notes',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMyMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=datetime.date.today, null=True)),
                ('pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.pin')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Dexa_historique_my_map',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueExplorer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateField(default=datetime.date.today, null=True)),
                ('pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.pin')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Dexa_historique_explorer',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.CharField(choices=[('C_V', 'Contrat de vente'), ('C_L', 'Contrat de location')], max_length=40, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='doc_pins_my_map/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('pin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.pin')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Dexa_documents',
            },
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['username'], name='Dexa_pin_usernam_5dcc93_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['deleted'], name='Dexa_pin_deleted_5fbfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['is_validate_by_user'], name='Dexa_pin_is_vali_a12fac_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['region'], name='Dexa_pin_region__00c7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['type_de_reference'], name='Dexa_pin_type_de_9b0d00_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['type_de_bien'], name='Dexa_pin_type_de_c221c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('editer_par', 'pin')},
        ),
    ]
