# Generated by Django 3.2.7 on 2021-09-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='from_table',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
