# Generated by Django 3.2.7 on 2021-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_map', '0002_pin_from_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='from_table',
            field=models.CharField(default='D', max_length=1, null=True),
        ),
    ]
