# Generated by Django 3.2.7 on 2021-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_map', '0005_auto_20210923_0507'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pin',
            name='api_map_pin_usernam_781a3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pin',
            name='api_map_pin_deleted_d56185_idx',
        ),
        migrations.RemoveIndex(
            model_name='pin',
            name='api_map_pin_is_vali_acd519_idx',
        ),
        migrations.RemoveIndex(
            model_name='pin',
            name='api_map_pin_region__9a3621_idx',
        ),
        migrations.RemoveIndex(
            model_name='pin',
            name='api_map_pin_type_de_d867f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='pin',
            name='api_map_pin_type_de_457e37_idx',
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['username'], name='Dexa_pin_usernam_5dcc93_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['deleted'], name='Dexa_pin_deleted_5fbfcd_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['is_validate_by_user'], name='Dexa_pin_is_vali_a12fac_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['region'], name='Dexa_pin_region__00c7ef_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['type_de_reference'], name='Dexa_pin_type_de_9b0d00_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['type_de_bien'], name='Dexa_pin_type_de_c221c5_idx'),
        ),
        migrations.AlterModelTable(
            name='documents',
            table='Dexa_documents',
        ),
        migrations.AlterModelTable(
            name='historiqueexplorer',
            table='Dexa_historique_explorer',
        ),
        migrations.AlterModelTable(
            name='historiquemymap',
            table='Dexa_historique_my_map',
        ),
        migrations.AlterModelTable(
            name='note',
            table='Dexa_notes',
        ),
        migrations.AlterModelTable(
            name='photographie',
            table='Dexa_photographies',
        ),
        migrations.AlterModelTable(
            name='pin',
            table='Dexa_pin',
        ),
        migrations.AlterModelTable(
            name='tags',
            table='Dexa_tags',
        ),
    ]
