# Generated by Django 3.2.7 on 2021-09-21 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='credit',
            table='Credit',
        ),
        migrations.AlterModelTable(
            name='facture',
            table='Facture',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
