# Generated by Django 3.2.7 on 2021-09-24 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210921_1326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='credit',
            table='User_credit',
        ),
        migrations.AlterModelTable(
            name='facture',
            table='User_facture',
        ),
    ]
