# Generated by Django 3.2.7 on 2021-09-21 09:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clients', '0001_initial'),
        ('gestion_dgi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/rapport/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('descriptif', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'rapport_photographie',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('lng', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('prix_unit_estime', models.BigIntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('type_de_bien', models.IntegerField(blank=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_clients.client')),
                ('dgi_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_dgi.dgi_appt_casa')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapport_generer',
            },
        ),
    ]
