# Generated by Django 3.2.7 on 2021-09-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afficher_box_rapport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='descreptif',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
