# Generated by Django 3.2.7 on 2021-09-20 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_dgi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('afficher_box_rapport', '0002_client_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('lng', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('prix_unit_estime', models.BigIntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('dgi_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_dgi.dgi_appt_casa')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rapport_generer',
            },
        ),
    ]
