# Generated by Django 3.2.7 on 2021-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afficher_box_rapport', '0002_rapport_descreptif'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='from_table',
            field=models.CharField(default='R', max_length=1, null=True),
        ),
    ]
