# Generated by Django 3.2.7 on 2021-09-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('afficher_box_rapport', '0003_rapport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='afficher_box_rapport.client'),
        ),
    ]
