# Generated by Django 3.2.7 on 2021-09-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afficher_box_rapport', '0003_rapport_from_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='photographie',
            table='Rapport_photographie',
        ),
        migrations.AlterModelTable(
            name='rapport',
            table='Rapport_generer',
        ),
    ]
