# Generated by Django 3.2.7 on 2021-09-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afficher_box_rapport', '0004_rapport_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='Clients',
        ),
    ]
