# Generated by Django 3.2.7 on 2021-09-24 15:48

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_dgi', '0002_alter_dgi_appt_casa_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_clients', '0002_delete_situationjuridique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photographie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/rapport/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('descriptif', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'Rapport_photographie',
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('lng', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('prix_unit_estime', models.BigIntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('type_de_bien', models.IntegerField(blank=True, null=True)),
                ('descreptif', models.IntegerField(blank=True, null=True)),
                ('from_table', models.CharField(default='R', max_length=1, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('descriptif_age_imm', models.IntegerField(blank=True, null=True)),
                ('descriptif_nbr_niv', models.IntegerField(blank=True, null=True)),
                ('descriptif_niv', models.IntegerField(blank=True, null=True)),
                ('descriptif_nbr_appt_etage', models.IntegerField(blank=True, null=True)),
                ('descriptif_ascenceur', models.IntegerField(blank=True, null=True)),
                ('descriptif_stationnement', models.IntegerField(blank=True, null=True)),
                ('descriptif_exploitation_etage', models.IntegerField(blank=True, null=True)),
                ('descriptif_exploitation_rdc', models.IntegerField(blank=True, null=True)),
                ('descriptif_securite', models.IntegerField(blank=True, null=True)),
                ('descriptif_acces_mob_reduite', models.IntegerField(blank=True, null=True)),
                ('descriptif_composistion', models.IntegerField(blank=True, null=True)),
                ('descriptif_donne_sur', models.IntegerField(blank=True, null=True)),
                ('descriptif_orientation', models.IntegerField(blank=True, null=True)),
                ('descriptif_chambr_sol', models.IntegerField(blank=True, null=True)),
                ('descriptif_chambr_mur', models.IntegerField(blank=True, null=True)),
                ('descriptif_chambr_plafon', models.IntegerField(blank=True, null=True)),
                ('descriptif_cuisine_sol', models.IntegerField(blank=True, null=True)),
                ('descriptif_cuisine_mur', models.IntegerField(blank=True, null=True)),
                ('descriptif_cuisine_plafon', models.IntegerField(blank=True, null=True)),
                ('descriptif_wc_sol', models.IntegerField(blank=True, null=True)),
                ('descriptif_wc_mur', models.IntegerField(blank=True, null=True)),
                ('descriptif_wc_plafon', models.IntegerField(blank=True, null=True)),
                ('descriptif_hall_salon_sol', models.IntegerField(blank=True, null=True)),
                ('descriptif_hall_salon_mur', models.IntegerField(blank=True, null=True)),
                ('descriptif_hall_salon_plafon', models.IntegerField(blank=True, null=True)),
                ('descriptif_climatiseur', models.IntegerField(blank=True, null=True)),
                ('descriptif_sdb', models.IntegerField(blank=True, null=True)),
                ('descriptif_cuisine_equip', models.IntegerField(blank=True, null=True)),
                ('titre_foncier', models.CharField(max_length=9, null=True)),
                ('date_cp', models.DateField(default=datetime.date.today, null=True)),
                ('surface_titree', models.IntegerField(blank=True, null=True)),
                ('conservation', models.CharField(max_length=50, null=True)),
                ('fraction', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, null=True, size=None)),
                ('hypotheque', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, null=True, size=None)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_clients.client')),
                ('dgi_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_dgi.dgi_appt_casa')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rapport_generer',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('reponse_pour', models.IntegerField(blank=True, null=True)),
                ('rapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_rapports.rapport')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rapport_commentaire',
                'unique_together': {('username', 'rapport')},
            },
        ),
    ]
