# Generated by Django 4.0.2 on 2022-02-03 16:12

import datetime
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_dgi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_dossier_interne', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('lat', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('lng', models.DecimalField(decimal_places=18, max_digits=20, null=True)),
                ('montant_demande', models.BigIntegerField(blank=True, null=True)),
                ('prix_unit_estime', models.BigIntegerField(blank=True, null=True)),
                ('asking_price', models.BigIntegerField(blank=True, null=True)),
                ('is_locked', models.BooleanField(blank=True, default=False, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('type_de_bien', models.IntegerField(blank=True, null=True)),
                ('descreptif', models.IntegerField(blank=True, null=True)),
                ('from_table', models.CharField(default='R', max_length=1, null=True)),
                ('score', models.DecimalField(decimal_places=9, default='0.5', max_digits=10, null=True)),
                ('descriptif_age_imm', models.IntegerField(blank=True, null=True)),
                ('descriptif_nbr_niv', models.IntegerField(blank=True, null=True)),
                ('descriptif_niv', models.IntegerField(blank=True, null=True)),
                ('descriptif_nbr_appt_etage', models.IntegerField(blank=True, null=True)),
                ('descriptif_ascenceur', models.IntegerField(blank=True, null=True)),
                ('descriptif_stationnement', models.IntegerField(blank=True, null=True)),
                ('descriptif_exploitation_etage', models.IntegerField(blank=True, null=True)),
                ('descriptif_exploitation_rdc', models.IntegerField(blank=True, null=True)),
                ('descriptif_securiteAccInterphone', models.IntegerField(blank=True, null=True)),
                ('descriptif_securiteRes', models.IntegerField(blank=True, null=True)),
                ('descriptif_acces_mob_reduite', models.IntegerField(blank=True, null=True)),
                ('descriptif_composistion_cuisine', models.IntegerField(blank=True, null=True)),
                ('descriptif_composistion_sdb', models.IntegerField(blank=True, null=True)),
                ('descriptif_composistion_salon', models.IntegerField(blank=True, null=True)),
                ('descriptif_composistion_chambre', models.IntegerField(blank=True, null=True)),
                ('descriptif_donne_sur', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('descriptif_orientation', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('descriptif_chambr_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_chambr_mur', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_chambr_plafon', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_cuisine_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_cuisine_mur', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_cuisine_plafon', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_wc_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_wc_mur', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_wc_plafon', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_hall_salon_sol', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_hall_salon_mur', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_hall_salon_plafon', models.CharField(blank=True, max_length=50, null=True)),
                ('descriptif_fenetres', models.IntegerField(blank=True, null=True)),
                ('descriptif_type_aluminum', models.IntegerField(blank=True, null=True)),
                ('descriptif_fenetres_manuel_electrique', models.IntegerField(blank=True, null=True)),
                ('descriptif_portes', models.IntegerField(blank=True, null=True)),
                ('descriptif_climatiseur', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('descriptif_sdb', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None)),
                ('descriptif_cuisine_equip', models.IntegerField(blank=True, null=True)),
                ('titre_foncier', models.CharField(max_length=9, null=True)),
                ('date_cp', models.DateField(default=datetime.date.today, null=True)),
                ('surface_titree', models.IntegerField(blank=True, null=True)),
                ('conservation', models.CharField(max_length=50, null=True)),
                ('fraction', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, default='{}', null=True, size=None)),
                ('hypotheque', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, default='{}', null=True, size=None)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_clients.clientphysique')),
                ('dgi_zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_dgi.dgi_appt_casa')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotographieRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/rapport/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg', 'tiff'])])),
                ('descriptif', models.CharField(max_length=200, null=True)),
                ('rapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_rapports.rapport')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentsRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.CharField(choices=[('C_V', 'Contrat de vente'), ('C_P', 'Certificat de propriété'), ('P_C', 'Plan de cdastre')], max_length=40, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='doc_pins_my_map/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('rapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_rapports.rapport')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rapport_documents',
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=300, null=True)),
                ('date', models.DateField(default=datetime.date.today, null=True)),
                ('reponse_pour', models.IntegerField(blank=True, default='0', null=True)),
                ('rapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_rapports.rapport')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rapport_commentaire',
            },
        ),
    ]
