# Generated by Django 3.2.7 on 2021-09-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentaire',
            table=None,
        ),
        migrations.AlterModelTable(
            name='photographie',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rapport',
            table=None,
        ),
    ]
