# Generated by Django 3.2.7 on 2021-09-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='montant_demande',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='ref_dossier_interne',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
    ]
