# Generated by Django 3.2.7 on 2021-09-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0003_rapport_asking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='ref_dossier_interne',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
