# Generated by Django 3.2.7 on 2021-09-28 08:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_rapports', '0006_alter_rapport_hypotheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.CharField(choices=[('C_V', 'Contrat de vente'), ('C_P', 'Certificat de propriété'), ('P_C', 'Plan de cdastre')], max_length=40, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='doc_pins_my_map/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('rapport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_rapports.rapport')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Rapport_documents',
            },
        ),
    ]
