# Generated by Django 3.2.7 on 2021-09-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0007_documentsrapport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photographie',
            new_name='PhotographieRapport',
        ),
    ]
