# Generated by Django 3.2.7 on 2021-09-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0009_photographierapport_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='reponse_pour',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
