# Generated by Django 3.2.7 on 2021-09-28 14:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0010_alter_commentaire_reponse_pour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='fraction',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, default='[]', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='hypotheque',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25, null=True), size=None), blank=True, default='[]', null=True, size=None),
        ),
    ]
