# Generated by Django 3.2.7 on 2021-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0013_auto_20210928_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='score',
            field=models.IntegerField(blank=True, default='0.5', null=True),
        ),
    ]
