# Generated by Django 3.2.7 on 2021-09-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0014_alter_rapport_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='descriptif_composistion',
            new_name='descriptif_composistion_chambre',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='descriptif_securite',
            new_name='descriptif_composistion_cuisine',
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_composistion_salon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_composistion_sdb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_securiteAccInterphone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_securiteRes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
