# Generated by Django 3.2.7 on 2021-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0015_auto_20210930_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='descriptif_fenetres',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_fenetres_manuel_electrique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_portes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='descriptif_type_aluminum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
