# Generated by Django 3.2.7 on 2021-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0019_auto_20210930_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_chambr_mur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_chambr_plafon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_chambr_sol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_cuisine_mur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_cuisine_plafon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_cuisine_sol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_hall_salon_mur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_hall_salon_plafon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_hall_salon_sol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_wc_mur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_wc_plafon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='descriptif_wc_sol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
