# Generated by Django 3.2.7 on 2021-10-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rapports', '0020_auto_20210930_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='score',
            field=models.DecimalField(decimal_places=9, default='0.5', max_digits=10, null=True),
        ),
    ]
