"""
Django settings for realtysoft project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mmllkykawb35x5vq3e_r8#q#4zzdj7*8w6q=)!&%!alx!gi-_='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'dexamap.ma', '192.168.1.85']
ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True
APPEND_SLASH=False

# Application definition

INSTALLED_APPS = [
    #'accounts',
    'account.apps.AccountConfig',
    'afficher_box_plus_info.apps.AfficherBoxPlusInfoConfig',
    'afficher_box_rapport.apps.AfficherBoxRapportConfig',
    'api_map.apps.ApiMapConfig',
    'apis.apps.ApisConfig',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.gis',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sessions',
    'filtrage_ref.apps.FiltrageRefConfig',
    'gestion_clients.apps.GestionClientsConfig',
    'gestion_commentaires_ref.apps.GestionCommentairesRefConfig',
    'gestion_csv.apps.GestionCsvConfig',
    'gestion_dgi.apps.GestionDgiConfig',
    'gestion_documents_ref.apps.GestionDocumentsRefConfig',
    'gestion_photos_ref.apps.GestionPhotosRefConfig',
    'gestion_ref.apps.GestionRefConfig',
    'gestion_tags_ref.apps.GestionTagsRefConfig',
    'quotes.apps.QuotesConfig',
    'rest_framework',
    'rest_framework.authtoken',
    #'whitenoise.runserver_nostatic',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'realtysoft.urls'

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 3600

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'realtysoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'mydb',
        'USER': 'postgres',
        'PASSWORD' : 'admin',
        'HOST': 'localhost'

    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "account.User"

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#STATIC_ROOT = "/var/www/localhost/static/"
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'realtysoft/static')
]
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#EMAILS
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "realtysoft.dexa@gmail.com"
EMAIL_HOST_PASSWORD = "mdpadmin123"
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

#RestFramework config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}
try:
    from .logger_settings import *
except Exception as e:
    # in case of any error, pass silently.
    pass

if os.name == 'nt':
    OSGEO4W = r"C:\OSGeo4W"
    #if '64' in platform.architecture()[0]:
    #    OSGEO4W += "64"
    assert os.path.isdir(OSGEO4W), "Directory does not exist: " + OSGEO4W
    os.environ['OSGEO4W_ROOT'] = OSGEO4W
    os.environ['GDAL_DATA'] = OSGEO4W + r"\share\gdal"
    os.environ['PROJ_LIB'] = OSGEO4W + r"\share\proj"
    os.environ['PATH'] = OSGEO4W + r"\bin;" + os.environ['PATH']
    
GDAL_LIBRARY_PATH = r'C:\OSGeo4W\bin\gdal303'