# Generated by Django 4.0.2 on 2022-02-03 16:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dgi_appt_casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('sous_type', models.CharField(blank=True, choices=[('r', 'récent'), ('r_f', 'récent et fermé'), ('a', 'ancien'), ('a_f', 'ancien et fermé')], default='r', max_length=4, null=True)),
                ('prix_unit', models.BigIntegerField(blank=True, null=True)),
                ('type_de_bien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.typebien')),
                ('ville', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_map.villes')),
            ],
            options={
                'db_table': 'Dgi_appt_casa',
            },
        ),
    ]
