# Generated by Django 3.2.7 on 2021-09-21 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_dgi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dgi_appt_casa',
            table='Dgi_appt_casa',
        ),
    ]
