# Generated by Django 3.2.7 on 2021-09-16 10:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table_devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telephone', models.CharField(max_length=10, null=True)),
                ('societe', models.CharField(max_length=200, null=True)),
                ('secteur', models.CharField(choices=[('Autre', 'Autre'), ('SG_AM', 'Société de gestion / Asset management'), ('B_L', 'Banque / Leasing'), ('P_D', 'Promoteur / Développeur'), ('TI', 'Transaction en immobilier'), ('C_EI', 'Conseil / Expertise en immobilier')], max_length=5, null=True)),
                ('message', models.TextField(null=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='devis/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('montant_HT', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('V', 'validé'), ('NV', 'en cours de traitement')], default='NV', max_length=2)),
            ],
        ),
    ]
